version: '2'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    command: bash ./run-test.sh
